---
name: Deploy Website with surge
on:
  push:
    branches:
      - main
jobs:
  build:
    name: job_deploy_surge
    runs-on: ubuntu_latest
    steps:
      - uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: setup surge
        run: npm install --global surge
      - name: Execute deployment with surge
        run: surge ./ project001.surge.sh  --token ${{secrets.SURGE_TOKEN_SECRET}}
          
